### ISSUE TITLE
Avoid connecting river basins through drainage ditches

### ISSUE THREAD

**Issue by dch0ph** [amandasaurus/waterwaymap.org#11]
At least in the UK, it is noticeable that several river basins are being merged into unreasonably large basins.

This seems to be happening in poorly drained upper moorland areas where drainage ditches are crossing e.g.:

![image](https://github.com/amandasaurus/waterwaymap.org/assets/20069699/65119e04-b98c-440a-94e4-ef2fb53e998c)
In the JOSM view, the cross-cutting drainage ditches in the centre drain in different directions, but have the effect of joining unconnected basins, i.e. the concept of a watershed is being lost.

I think a simple fix would be to ignore the crossing of waterway=drain/ditch (unfortunately these seemed to be used interchangeably). OK this will leave some isolated fragments, but this is better than everything ending up merged together (which is what seems to be happening in Northern England).

But this is a great tool for spotting connectivity issues!

**Comment by amandasaurus** [comment]
On Fr, 03 Nov 2023 21:49 +01:00, dch0ph ***@***.***> wrote:
> I think a simple fix would be to ignore the crossing of 
> waterway=drain/ditch (unfortunately these seemed to be used 
> interchangeably).

Do you know about the [“River or Stream” view](https://waterwaymap.org/#map=6.79/53.722/-0.117&tiles=planet-waterway-river-stream)? It it's only `waterway=river` or `=stream`. That does part of what you want, no?


> At least in the UK, it is noticeable that several rive basins are being 
> merged into unreasonably large basins.

Have you not seen the Central European Massive Water Basin? 🤣 It's an unfortunate outcome of the simple algorithm meeting the real world. (This could be a motto for so many things that use OSM data)

---

> In the JOSM view, the cross-cutting drainage ditches in the centre 
> drain in different directions, but have the effect of joining 
> unconnected basins, i.e. the concept of a watershed is being lost.

FYI I plan to make something that takes waterway direction into account.


-- 
Amanda
