### ISSUE TITLE
Add `waterway=rapids` to the river-stream filter

### ISSUE THREAD

**Issue by mcliquid** [amandasaurus/waterwaymap.org#14]
Link: https://waterwaymap.org/#map=14.53/47.39652/10.27678&len=10..100000&tiles=planet-waterway-river-stream
OSM: https://www.openstreetmap.org/way/1158992385

I'm not quite sure, but I would include it as "rapids" is just a more accurate term for a steeply sloping riverbed. It's nothing artificial and is somehow part of it. There should actually be a lot more "rapids" in OSM, as every natural river in the Alps has them.

**Comment by amandasaurus** [comment]
🤔
Doesn't the [waterway w/o some “dam” values](https://waterwaymap.org/#map=10.62%2F47.372%2F10.4312&tiles=planet-waterway-excl-non-waterway) map work for that? I don't want to duplicate that map (but approaching from the other direction)
