### ISSUE TITLE
Blurry tiles as a result of 512px default

### ISSUE THREAD

**Issue by 2hu4u** [amandasaurus/waterwaymap.org#16]
The OSM basemap tiles are 256 but Maplibre assumes default of 512 resulting in blurry tiles being displayed. I believe this can be fixed by adding the tileSize line into your setup.js;
```
"osmcarto": {
					type: "raster",
					tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
					tileSize: 256,
					attribution: '© <a href="https://openstreetmap.org">OpenStreetMap</a>'
				},
```
Blurry tiles:
![Blurry tiles](https://github.com/amandasaurus/waterwaymap.org/assets/153789710/33a19e31-2f18-4a4d-9ea9-733500ce9817)
After fix:
![After fixing](https://github.com/amandasaurus/waterwaymap.org/assets/153789710/020f2670-f6fa-4ad6-b422-9312a5db218b)

**Comment by amandasaurus** [comment]
oh that looks much nicer! Thanks. I didn't know that was improveable. 👍
