### ISSUE TITLE
Portages?

### ISSUE THREAD

**Issue by osmuser63783** [amandasaurus/waterwaymap.org#17]
Looking at the canoe map I wonder if it might be useful to include portages, these are short trails that connect two navigable waterways, where you have to carry your canoe, [like this](https://www.google.com/search?q=portaging&tbm=isch). They are mapped with `canoe=portage` (in addition to a `highway`). As far as I know the waterways connected like this would usually be considered part of the same network for canoeing purposes. There are route planners like [this](https://www.paddleplanner.com/tools/maps/algonquinmap.aspx) that allow you to plot a route and show how much of it is canoeing and how much of it is portaging, etc. Such a view could be useful to spot portages missing in OSM data.

![Screenshot_20231221_113144_Firefox](https://github.com/amandasaurus/waterwaymap.org/assets/127188803/d43501a3-92ab-42b2-ab40-f0e69bbd7818)
https://www.openstreetmap.org/way/292380499

I should add, I don't canoe regularly, and it might be worth asking some people who know more about canoeing than me (e.g. reddit.com/r/canoecamping). Who knows, maybe this could even be an opportunity to get new contributors for OSM, if people find this tool useful and see how easy it is to correct and add any missing data :-)

**Comment by amandasaurus** [comment]
Fixed!

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1547/714082ab-3aa1-4400-b895-cead3162a78a)
