### ISSUE TITLE
Add waterway=reservoir to ignored tags

### ISSUE THREAD

**Issue by Danysan1** [amandasaurus/waterwaymap.org#18]
[`waterway=reservoir`](https://taginfo.openstreetmap.org/tags/waterway=reservoir#overview) is not documented but is used 138 times to map reservoirs, which are usually areas, causing false positives in the loop detector. I think this tag should be among the ignored tags.

PS: looking into this I noticed that [make-planet.sh](https://github.com/amandasaurus/waterwaymap.org/blob/4bf01002fe79f87f7709eaa78879ba6df47d9d1c/make-planet.sh#L36) contains `waterway=habour` among ignored tags but [that tag does not exist](https://taginfo.openstreetmap.org/search?q=waterway%3Dhabour#tags), maybe you meant [`waterway=harbour`](https://taginfo.openstreetmap.org/tags/waterway=harbour#overview)? Also, in [Makefile](https://github.com/amandasaurus/waterwaymap.org/blob/4bf01002fe79f87f7709eaa78879ba6df47d9d1c/Makefile#L79) that tag is not present.

**Comment by amandasaurus** [comment]
> [waterway=reservoir](https://taginfo.openstreetmap.org/tags/waterway=reservoir#overview) is not documented but is used 138 times to map reservoirs, which are usually areas, causing false positives in the loop detector

To me, that means we should keep them in. When people see the loop, they should fix it by changing the tags to the much more popular [`water=reservoir`](https://wiki.openstreetmap.org/wiki/Tag:water%3Dreservoir).

>[make-planet.sh](https://github.com/amandasaurus/waterwaymap.org/blob/4bf01002fe79f87f7709eaa78879ba6df47d9d1c/make-planet.sh#L36) contains waterway=habour among ignored tags but [that tag does not exist](https://taginfo.openstreetmap.org/search?q=waterway%3Dhabour#tags)

Oops. My mistake. I've removed it.

> maybe you meant [waterway=harbour](https://taginfo.openstreetmap.org/tags/waterway=harbour#overview)

There's only [11 of tag tag](https://taginfo.openstreetmap.org/tags/waterway=harbour#overview), which implies that `waterway=habor` is wrong. For the same reason as above, I'll keep it in the loop detection to improve the OSM tags.

**Comment by Danysan1** [comment]
Makes sense, closing this.

Thanks for your work.
