### ISSUE TITLE
waterway=reservoir loop?

### ISSUE THREAD

**Issue by matozoid** [amandasaurus/waterwaymap.org#19]
Hi! I found this and am not sure if it is a mapping mistake: https://waterwaymap.org/loops/#map=17.65/50.606988/6.10547

**Comment by amandasaurus** [comment]
That looks like a mapping mistakes. It ([w1028660742](https://www.openstreetmap.org/way/1028660742)) is tagged `waterway=reservoir`, and it shouldn't have that tag.
