### ISSUE TITLE
Waterway loop in fish pass

### ISSUE THREAD

**Issue by matozoid** [amandasaurus/waterwaymap.org#20]
As reported by @tordans@en.osm.town on Mastodon: https://waterwaymap.org/loops/#map=18.15/50.716291/6.446711

**Comment by amandasaurus** [comment]
I think that is a taggging mistake.

The [OSM Wiki for fish passes](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dfish_pass) says that the linear way is the `waterway=fish_pass`. For the area (which will have a loop), one should use `water=fish_pass`.
