### ISSUE TITLE
Loops feature density/filtering

### ISSUE THREAD

**Issue by maxerickson** [amandasaurus/waterwaymap.org#21]
In areas where there aren't many features, it seems the tile creation process is still omitting features, frustrating the process of finding the features with the likely issues.

Maybe a second tippecanoe command using '--cluster-densest-as-needed' instead of '--drop-densest-as-needed' for the mostly sparse data sets?

**Comment by amandasaurus** [comment]
oh thanks! That makes a map better. I wondered why one of the loops in Ireland would blink in & out of view
