### ISSUE TITLE
Off by one problem rendering waterway area

### ISSUE THREAD

**Issue by matozoid** [amandasaurus/waterwaymap.org#22]
When marking area's (that are erroneously tagged waterway), there always seems to be one node missing in the black line:

https://waterwaymap.org/loops/#map=17.03/50.478216/4.109867

![afbeelding](https://github.com/amandasaurus/waterwaymap.org/assets/55701/8bea8de4-c284-4652-b025-e0c8ff26cec8)

**Comment by amandasaurus** [comment]
The code uses `tippecanoe` to simplify the geometry. I wonder if that's what's going on here?

**Comment by amandasaurus** [comment]
I think this is just a rendering issue with tippe canoe simplified geom.
