### ISSUE TITLE
Add loading progress bar

### ISSUE THREAD

**Issue by JesseWeinstein** [amandasaurus/waterwaymap.org#25]
It's hard to tell when there aren't any loops visible because there aren't any there, or because they haven't loaded yet. Some visual indication would be helpful.

**Comment by amandasaurus** [comment]
that sounds like a good idea, but I don't know how to do that. I don't know how to make maplibre do it.

I'm surpirsed you find that necessary, the loops file, is a small (<20MiB) pmtiles vector tiles file. If it's taking a while, there could be a problem with your computer or internet connection

**Comment by JesseWeinstein** [comment]
It's not so much that it takes a while, it's that I'm unsure if it's loaded all of them (and there just aren't any/many) or if it's still loading.

From https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.MapEventType/ it looks like the `sourcedataloading` and `sourcedata` events are the relevant ones to hook into. I'll try and make a PR this weekend.

**Comment by amandasaurus** [comment]
On Sa, 13 Jan 2024  1:14 +01:00, JesseWeinstein ***@***.***> wrote:
> It's not so much that it takes a while, it's that I'm unsure if it's 
> loaded all of them (and there just aren't any/many) or if it's still 
> loading.

The programme that converts the geojson to vectortiles ([`tippecanoe`](https://github.com/felt/tippecanoe)) does [drop some features](https://github.com/felt/tippecanoe#dropping-a-fixed-fraction-of-features-by-zoom-level) to stay within sensible tile sizes. in [the Makefile](https://github.com/amandasaurus/waterwaymap.org/blob/main/Makefile#L117-L132) you can see how I call that programme.

IME features are sometimes included in some, but not all zoom levels. I've seen a feature blink in and out when zooming in. Perhaps this is what you are seeing?

It's possible tippecanoe could be better called to *not* do that. If you know how to do that, then go ahead. 🙂

> From 
> https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.MapEventType/ 
> it looks like the `sourcedataloading` and `sourcedata` events are the 
> relevant ones to hook into. I'll try and make a PR this weekend.

Oh if you have a PR that's much easier for me to accept 🙂
-- 
Amanda.,

**Comment by amandasaurus** [comment]
On Sa, 13 Jan 2024 10:38 +01:00, Amanda ***@***.***> wrote:
> The programme that converts the geojson to vectortiles 
> ([`tippecanoe`](https://github.com/felt/tippecanoe)) does [drop some 
> features](https://github.com/felt/tippecanoe#dropping-a-fixed-fraction-of-features-by-zoom-level) 
> to stay within sensible tile sizes. in [the 
> Makefile](https://github.com/amandasaurus/waterwaymap.org/blob/main/Makefile#L117-L132) 
> you can see how I call that programme. 
>
> IME features are sometimes included in some, but not all zoom levels. 
> I've seen a feature blink in and out when zooming in. Perhaps this is 
> what you are seeing? 
>
> It's possible tippecanoe could be better called to *not* do that. If 
> you know how to do that, then go ahead. 🙂 

I have changed the code to upload the `.geojsons` which is used to create the cycles. It's got the same URL as the `planet-cycles.pmtiles`, but `.geojsons`. Feel free to download it (it's < 50 MiB) and try to generate a better pmtiles.

🙂
-- 
Amanda

**Comment by JesseWeinstein** [comment]
Here's the PR I promised. Not sure if this is exactly the best way to do it, but it seems to work for me at least: https://github.com/amandasaurus/waterwaymap.org/pull/27
