### ISSUE TITLE
Waterway=drain shall not be counted as a "Natural waterway"

### ISSUE THREAD

**Issue by jmacura** [amandasaurus/waterwaymap.org#28]
Hi,
thanks for this very nice waterway visualisation!

I have a proposal for a one small change. As of now, the waterways with `waterway=drain` count towards the group "Natural Waterways", which seems incorrect to me, as these are artificial features.

I think the change shall be as simple as adding another value in this line:
https://github.com/amandasaurus/waterwaymap.org/blob/86300d0b94a807259a034127bc4d6ec762f14658/Makefile#L101
but I have zero knowledge of shell scripts so I do not have the courage to open a PR directly.

Thanks for considering this!

**Comment by amandasaurus** [comment]
On Mo, 22 Jan 2024 22:56 +01:00, jmacura ***@***.***> wrote:
> thanks for this very nice waterway visualisation!

Thanks! 😁

> I have a proposal for a one small change. As of now, the waterways with 
> `waterway=drain` count towards the group "Natural Waterways", which 
> seems incorrect to me, as these are artificial features.

Yes that sounds sensible.

> I think the change shall be as simple as adding another value in this 
> line:
> https://github.com/amandasaurus/waterwaymap.org/blob/86300d0b94a807259a034127bc4d6ec762f14658/Makefile#L101

Yes, it would go there.

> but I have zero knowledge of shell scripts so I do not have the courage 
> to open a PR directly.

If you want to learn how to this sort of thing, you can just try! Please feel free if you want!

_(If you don't want to, I can make the change myself easily)_.

-- 
Amanda

**Comment by amandasaurus** [comment]
I've made the change myself. 🙂

**Comment by jmacura** [comment]
> I've made the change myself. 🙂

Thanks for that!
I intended to give it a try but haven't find the time... 😞
