### ISSUE TITLE
[Feature Request] Hide/Show the Header 

### ISSUE THREAD

**Issue by limex** [amandasaurus/waterwaymap.org#35]
Hi,
the header is consuming too much space. Can you add a button for that?

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1173039/42e0485e-a0ba-4f5f-8746-775685216c45)

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1173039/886bbf81-bde3-42ae-b8ea-18cdd310a94a)

The snippet would be something like:

```
<header x-data="{ open: false }">
    <button @click="open = !open">Toggle Header</button>
    <div x-show="open">
        <h1 class=inline_centre style="margin: 0; margin-top: 0.3ch;"><img src="img/osm.png" alt="OpenStreetMap logo" style="height: 1em"><span>🏞️ WaterwayMap</span></h1>
        <!-- Rest of your header content goes here -->
        
        <!-- ... -->

        <!-- Make sure all content you want to be collapsible is wrapped in this div with x-show directive -->
    </div>
</header>
```

I tested the snipped, it works in the Dev Tools.
BR Günther

**Comment by limex** [comment]
done.

**Comment by amandasaurus** [comment]
done ages ago
