### ISSUE TITLE
Different colors for connected waterways

### ISSUE THREAD

**Issue by zstadler** [amandasaurus/waterwaymap.org#44]
The map shows a change of color [here](![image](https://github.com/amandasaurus/waterwaymap.org/assets/1304610/749d90dd-98e1-4090-9d00-77ee0ecf04ea)):

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1304610/27867749-f3aa-434a-b638-0bd7a04eb015)

However, the upstream and downstream are connected by [this node](https://www.openstreetmap.org/node/3308311234):

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1304610/a92c3c4c-38ef-470b-b6b7-56b60dd143e0)

What am I missing?

**Comment by amandasaurus** [comment]
It seems to be fixed now?

link: https://waterwaymap.org/#map=16.66/31.356673/35.315591

![image](https://github.com/amandasaurus/waterwaymap.org/assets/1547/3c73494f-bf16-4833-98ed-ccde835db7e9)

When did you see this map? I see the ways were changed about 4 days ago? WWM only updates once a day.
