### ISSUE TITLE
Exclude waterway=pressurised from Natural Waterways overlay

### ISSUE THREAD

**Issue by hungerburg** [amandasaurus/waterwaymap.org#47]
I see them a lot here, I am in the Alps, hydropower galore! They also connect across watersheds so false basin assigned.

**Comment by flacombe** [comment]
Hello @amandasaurus 

Despite waterxay=pressurised isn't natural waterways, water do flow through them.
Sometimes they divert significant amount of water from natural courses

`flowing_water.tagfilterfunc` sounds to detect flowing water, not only natural courses, aren't you?

**Comment by amandasaurus** [comment]
Yes it should detect flowing water. But if it's being pressurised, then the water is being (artificially) pushed somewhere. I want to map "naturally flowing water". Do you have an example of an OSM way which is tagged like this and is naturally flowing? Is there another tag combination that we can look at?

**Comment by hungerburg** [comment]
Perhaps the question is, why flagging them in this filter does not hide them from the flowing water plot, but only from the natural water plot?

PS: In Austria there are 522 pressurized waterways. 502 of them are pipelines, the rest flooded tunnels.  Certainly, in all of them water flows the **natural** direction indicated by gravity, i.e. from top to bottom, most of the time. Very few go to pump-storage and are **artificially pushed**, in the strictest sense ;) They some times change direction. There are even times, when the water does not flow, this can happen to all of them, e.g. when there is enough power on the market.

**Comment by amandasaurus** [comment]
OK, now I'm confused. 😅🤔.

*If* the water in `waterway=pressurised` is free flowing, then it should be included in `flowingwater`.

Yes, it might join up river basins, but (i) that happens anyway with natural river bifurations (ii) I have a solution for that 🤫

**Comment by flacombe** [comment]
Hello all

> I want to map "naturally flowing water".

Well, I know it looks simpler but it actually doesn't.  
Hydrography connectivity as pursued by waterwaymap needs both natural and artificial flows.

This table classifies natural/artificial versus free/pipe flows: https://wiki.openstreetmap.org/wiki/Key:waterway#Values
We currently miss natural pipe flow value(s) but it actually exists: caves which are constantly underwater (inverted siphons).

> If the water in waterway=pressurised is free flowing

Gravitational flow and free flowing are different.  
Free flowing is flowing at atmospheric pressure, like a river.

> Yes, it might join up river basins

It can not only joint up river basins but also divert water from natural course in the same basin, or connect two natural sections of a single river.
Removing channelized sections may break up the same basin in two parts.

Hope it helps

**Comment by hungerburg** [comment]
1) For what I can tell: A waterway=pressurized must not be shown in the natural plane. It is only used on constructions for hydropower by the mapping few, at least in the area of my local knowledge.
2) I would not bet that if I jumped into a flooded tunnel (as mapped by the few) that I would always have air space, like the diagram purports. There is no need to insert a pipe to flood a tunnel to the brim.

> We currently miss natural pipe flow value

I'd never tag a waterway=pressurized there - any examples in the wild? These certainly would be in need of a special tag, IMO.

BTW: The table picture does not show the most common (at least I suppose) use of penstock.

**Comment by flacombe** [comment]
> A waterway=pressurized must not be shown in the natural plane. It is only used on constructions for hydropower by the mapping few, at least in the area of my local knowledge.

You can't tell until you add some artificial structure containing it: 
* man_made=pipeline => artificial
* tunnel=flooded => artificial
* natural=cave => natural

> I would not bet that if I jumped into a flooded tunnel (as mapped by the few) that I would always have air space

tunnel=flooded is only intended to state the tunnel isn't designed to allow people to safely walk in operation. It doesn't assume of the flowing regime, free or pipe flow. It can be combined both with waterway=canal or with waterway=pressurised.

> I'd never tag a waterway=pressurized there - any examples in the wild? These certainly would be in need of a special tag, IMO.

Any cave where you dive in: https://timesofindia.indiatimes.com/travel/norway/plura-river-cave-diving/ps37309226.cms
This is pipe flow.

> The table picture does not show the most common (at least I suppose) use of penstock.

What should be shown according to you?

**Comment by hungerburg** [comment]
There is another picture of yours here https://wiki.openstreetmap.org/wiki/File:Waterways_millrace.png showing better what I think penstock is about. A similar graphic here page 10 https://www.ewa-services.at/files/broschuere_kw_kartell.pdf#page=10&zoom=page-fit,-2,760 - headrace pressurised up to the surge tank -- This one actually [mapped](https://www.openstreetmap.org/node/3206274325) -- The pipeline should be split there?

> Any cave where you dive in

But how is it mapped? As a waterway=pressurized? I'd consider that wrong.

**Comment by hungerburg** [comment]
@flacombe I guess I am starting to see. This is not about what the mapping community does. It is about your idea, how the tag could be used outside of the hydropower scheme.

In my opinion, the mapping community is right in not using the tag like this:

This would be akin to `highway=bridge|tunnel`, don't you think?

**Comment by flacombe** [comment]
> how the tag could be used outside of the hydropower scheme.

The tag is not specific to hydropower.

> In my opinion, the mapping community is right in not using the tag like this:

We're still looking for a better solution, 6 years and counting.

> This would be akin to highway=bridge|tunnel, don't you think?

It's the strict opposite. waterway=pressurised doesn't assume its container.

**Comment by hungerburg** [comment]
The solution is as easy as tagging `siphon=yes` on a river or a stream. Much like we do with bridges or tunnels.

**Comment by flacombe** [comment]
> The solution is as easy as tagging siphon=yes on a river or a stream.

Unfortunately, rivers or streams are free flow and can't be used to describe pipe water flows.

That's why I suggest to integrate pressurised waterways into waterwaymap graph.

**Comment by hungerburg** [comment]
This got me a stream of 30+ e-mails. Following the talk, the gist of it to me: Natural non-artificial flows of water underground deserve one or more tags on their own yet to be found and not get filed under an engineering term?

PS: All kind of pipelines, tunnels and canals are in the waterwaymap graph, just not in the "natural" slice.

**Comment by flacombe** [comment]
> Natural non-artificial flows of water underground deserve one or more tags on their own yet to be found and not get filed under an engineering term?

I'll be all in, once we found the appropriate waterway=* value for that, but we still fail for that in the public discussion.

> PS: All kind of pipelines, tunnels and canals are in the waterwaymap graph, just not in the "natural" slice.

That's fine indeed, I didn't used the view selection accordingly to find them.

**Comment by amandasaurus** [comment]
> I analysed recent OSM data, and if I include `waterway=pressurized` then there are only 22 more loops than with the current approach of ignoring them. There are ~16,100 waterway loops in OSM now. So +22 isn't a lot. This shows that OSMers aren't causing many 
> 
> [Here's a GeoJSON](https://gist.github.com/amandasaurus/d208b822ce31732256699eabf58f7e42) of the “new loops” when you include `=pressurized`. 
>
> In comparison, someone recently [asked for `waterway=ditch`](https://github.com/amandasaurus/waterwaymap.org/issues/59) to be included. Although the wiki says ditches should be mapped how the water flows, there are [28,000 loops in `waterway=ditch`](https://github.com/amandasaurus/waterwaymap.org/issues/59#:~:text=there%20are%2028%2C000%20loops%20in%20just%20waterway%3Dditch%20alone.) alone!
> 
> Based on this, I will probably put `=pressurized` back into WWM's [“flowing water” category](https://github.com/amandasaurus/waterwaymap.org/blob/main/flowing_water.tagfilterfunc).

https://gist.github.com/amandasaurus/d208b822ce31732256699eabf58f7e42

**Comment by hungerburg** [comment]
The loops in the GeoJSON look like trivial mapping/tagging errors.

My suggestion was to treat pressurized same as canal -- hide it from the "natural" selection. Is that the same as the "flowing" selection? Perhaps "natural" can mean different things: Pipelines being part or not being part of?
