### ISSUE TITLE
Gaps on boundary splits

### ISSUE THREAD

**Issue by danieldegroot2** [amandasaurus/waterwaymap.org#5]
There are numerous places where an admin boundary part of a river splits in two ways. Only one is a river, the other is a boundary. This seems to confuse the script and creates a gap where the first next segment is. The second next segment and onwards will be fine. (it also still counts as the same river)

- [osm-river-basins](https://amandasaurus.github.io/osm-river-basins/#map=16.68/52.524085/-7.13727)
- [osm](https://www.openstreetmap.org/#map=19/52.52403/-7.13769)
- [id](https://www.openstreetmap.org/edit#map=18/52.52427/-7.13756)

Creating an issue here so it can be tracked.

<img src="https://user-images.githubusercontent.com/67521919/262054176-652fadd4-f6d0-4b04-9fed-54e48b66a301.png" width="500" height="300">

<img src="https://user-images.githubusercontent.com/67521919/262054585-93a80abd-d0a6-481a-ae1b-0396e0ded299.png" width="500" height="300">

Blue: River with boundary
Red: Split in river where boundary way splits off.
Purple: Boundary way split off from river, no river here.

**Comment by amandasaurus** [comment]
On Mon, 21 Aug 2023 16:32 +02:00, danieldegroot2 ***@***.***> wrote:
> There are numerous places where an admin boundary part of a river 
> splits in two ways. Only one is a river, the other is a boundary. This 
> seems to confuse the script and creates a gap where the first next 
> segment is. The second next segment and onwards will be fine. (it also 
> still counts as the same river)

This appears to be the same instance of [a similar reported bug](https://community.openstreetmap.org/t/osm-river-basins-website-to-show-how-are-rivers-in-osm-connected/102655/4)

-- 
Amanda

**Comment by amandasaurus** [comment]
Recent versions of this software don't have this problem anymore.
