### ISSUE TITLE
Identify rivers that ends on a stream

### ISSUE THREAD

**Issue by angoca** [amandasaurus/waterwaymap.org#52]
The correct way is that waterway=stream ends on waterway=river but not the opposite.

It will be interesting to have a section for them.

**Comment by amandasaurus** [comment]
The rule I always heard is “if you can jump over it, then it's a `=stream`, otherwise it's `=river`”. It's possible for a river to get narrower until it's a stream. So I don't think this is always a mapping mistake.

However I think it would be useful to highlight this cases, to allow mappers to find mistakes. I have an idea how to do it.

**Comment by amandasaurus** [comment]
Here's a first attempt: [`http://data.waterwaymap.org/planet-waterway-stream-ends.geojson`](http://data.waterwaymap.org/planet-waterway-stream-ends.geojson) *(data will not update)*

(As of now) It's a 22 MiB GeoJOSN file, with 110k Features. It's all the ways from the `flowing_water` filter, _excluding_ anything with `waterway=stream`. The normal “flowing water” filter is in [``flowing_water.tagfilterfunc`](https://github.com/amandasaurus/waterwaymap.org/blob/main/flowing_water.tagfilterfunc), I did a quick hack to exclude `=stream`: [`flowing_water_wo_streams.tagfilterfunc`](https://github.com/amandasaurus/waterwaymap.org/blob/main/flowing_water_wo_streams.tagfilterfunc)

Each point contains `upstream_m`, which is the totaly length of all upstream waterways which end here. This

You can download load this file into JOSM and work on the data.

Remember not all points are mapping mistakes. 🙂

Is this sort of data OK for you? If so, I can add it to the regular generation, and make a map based on that.

**Comment by amandasaurus** [comment]
@angoca @mxdanger  What do you think of that data file? Is that OK? Is that the sort of thing you want?

If so, I can generate that regularly and make some sort of web page.

**Comment by angoca** [comment]
Hi @amandasaurus, the file is great. It has helped me to correct these invalid transitions. 

https://www.instagram.com/p/C_a_JBmupEC/
https://x.com/OSM_Colombia/status/1830645693784170518

If you can generate it in a regularly basis it will be great.

**Comment by amandasaurus** [comment]
Excellent! 🙂.

You can download the file from [`data.waterwaymap.org/planet-waterway-stream-ends.geojson.gz`](https://data.waterwaymap.org/planet-waterway-stream-ends.geojson.gz). It's a zipped GeoJSON file that you open in JOSM (or any GIS software). _(NB: it's a different URL from [before](https://github.com/amandasaurus/waterwaymap.org/issues/52#:~:text=here's%20a%20first%20attempt).

[more docs](https://github.com/amandasaurus/waterwaymap.org?tab=readme-ov-file#where-things-turn-into-streams)

Have fun mapping. 🙂 If you have any more interesting ideas, please let me know. 🙂
