### ISSUE TITLE
An End when Stream becomes a Canal

### ISSUE THREAD

**Issue by angoca** [amandasaurus/waterwaymap.org#56]
I have found that the app shows an End, when a Stream becomes a Canal.

https://www.openstreetmap.org/node/10805613026/history

Is this an error? I don't think so, but I want to confirm.

**Comment by amandasaurus** [comment]
> I have found that the app shows an End, when a Stream becomes a Canal.
>
> https://www.openstreetmap.org/node/10805613026/history
>
> Is this an error? I don't think so, but I want to confirm.

This is not a mistake. WWM is configured with [rules for detecting if a way is “flowing water”](https://github.com/amandasaurus/waterwaymap.org/blob/main/flowing_water.tagfilterfunc). `=stream` is included, a plain `=canal` is not included. This tagging rules are used for the Ends map. So to WWM/Ends, this canal doesn't exist, and the waterway ends there.

Now, maybe the tagging rules for WWM are wrong. e.g. if there's a `lock=yes` tag, then [it is included](https://github.com/amandasaurus/waterwaymap.org/blob/a8380dfb7e87423821fa82a855cc64381cfc8932/flowing_water.tagfilterfunc#L18-L20). Perhaps this waterway is flowing water, and a canal. There's [some discussion on the forum](https://community.openstreetmap.org/t/the-end-of-waterway-map/108632/19) about whether this is a sensible rule.

-- 
Amanda
