### ISSUE TITLE
Consider underground pipelines that have subtance=water

### ISSUE THREAD

**Issue by kaleidoscopica** [amandasaurus/waterwaymap.org#57]
I came across a drainage tunnel someone had tagged as an underground pipeline (`layer=-1`, `location=underground`, `man_made=pipeline`). It connects two exposed drains on either end, just functioning as an underground tunnel in between them. The tags seem to be appropriate per https://wiki.openstreetmap.org/wiki/Key:tunnel, which indicates that "When the `waterway=*` runs underground for a considerable distance, you can use ... `man_made=pipeline` for sections built with tube assemblies". With this in mind, I wonder if WWM should account for pipelines that have `substance=water` in them.

One example is here https://www.openstreetmap.org/edit?editor=id#map=19/29.46003/-98.54983 -- currently WWM does not see this as a connection between the drains on either end.

**Comment by quincylvania** [comment]
I would say the example is mistagged since it's just underground drainage (it's not even clear if it's in a pipe). I would only use underground `man_made=pipeline` for things like pumped or pressurized flows, mainly found at industrial sites, waterworks, dams, etc.
