### ISSUE TITLE
Add Last Refreshed date

### ISSUE THREAD

**Issue by EwenH** [amandasaurus/waterwaymap.org#64]
When editing a complex area, the user sometimes would like to go back and review that area once the map waterway map process has updated. Currently there is no clear way to understand when the layers were last updated.

In the copyright statement area, add the last updated date, as "Last data refresh: 30-Jul-2024" 
If moused over or clicked, it will provide a popup or link to a web page to explain the approximate update schedule.

**Comment by amandasaurus** [comment]
![image](https://github.com/user-attachments/assets/1a1f1fc3-7fb2-473e-82b2-23960971300c)

if you click on the settings button, you can see the date & time of the last update. It shows the age of the OSM data used to make the map. FYI the data is updated in daily.

Does that fulfil your requirement?

_(yes I kwow it hasn't updates in a little while, I'm working on it)_

**Comment by amandasaurus** [comment]
I've [added](https://github.com/amandasaurus/waterwaymap.org/commit/d85ed2ae4617d5372ebc5b62a5c945ef6154bc81) the date of the update to the main map screen. It'll now show next to the OSM attribution.

![small screenshot of the corner of the screen on waterwaymap.org showing the datetime beside OSM attribution](https://github.com/user-attachments/assets/82e602b1-549d-494e-a16a-90b884f8800b)
