### ISSUE TITLE
Support waterway=fairway

### ISSUE THREAD

**Issue by ftrebien** [amandasaurus/waterwaymap.org#65]
I think waterway=fairway should be displayed. It's been used since 2009 and it and quite common, for example, in and around the Wadden Sea and the Danish straits.

**Comment by quincylvania** [comment]
The tool already seems to support waterway=fairway for the navigation views. The tag represents a route, not a water feature, so I don't think it should really be included in the water flow views. [Here is an example](https://www.openstreetmap.org/edit?editor=id#map=16/39.62563/-75.57935) of a place where the river and the channel do not line up and have different names, and are therefore mapped separately.

**Comment by ftrebien** [comment]
Well, dozens of fairways [here](https://waterwaymap.org/#map=10/53.0825/5.0563&tiles=planet-waterway-boatable) and [here](https://waterwaymap.org/#map=10/54.9772/10.4618&tiles=planet-waterway-boatable) do not show when I select Settings → Filter data → Navigable by boat. It seems like extra access tags like boat=* are required for them to be displayed, but a fairway is by definition navigable.
